### PR TITLE
Add gear spec file for Sisyphus

### PR DESCRIPTION
**Pull request by mastersin**

### CODE REVIEW

**Comment by NIR-Ginko** [comment]
I suppose in case of GPL licensing we need to include GPL headers in all XML files present in project.

**Comment by NIR-Ginko** [comment]
Anyway, is it correct to apply licensing to ADMX files? I mean... It's like personal configuration files.

**Comment by mastersin** [comment]
А вот я не знаю как лучше. У ADMX для mozilla лицензия MIT. А что конкретно смущает? Какой "кейс"?

**Comment by mastersin** [comment]
Merged in another commit.

**Pull request closed without merging**
